apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
    spec:
      containers:
        - name: ${SERVICE_NAME}
          image: ${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${SERVICE_NAME}:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: devtool-secret
            - secretRef:
                name: db-secret
            - secretRef:
                name: oauth2-secret
