apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-lib
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-lib
  template:
    metadata:
      labels:
        app: core-lib
    spec:
      containers:
        - name: core-lib
          image: ${DOCKER_REGISTRY}/lamld2510/core-lib:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: devtool-secret
            - secretRef:
                name: db-secret
            - secretRef:
                name: oauth2-secret
