spring:
  jackson:
    time-zone: ${TIME_ZONE:UTC}
  application:
    name: ${APP_NAME:mos-core-lib}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:https://keycloak.103.77.243.66.nip.io/realms/develop_tool_realm}
    public-routes:
      - "/v1/public/**"
      - "/swagger-ui/**"
      - "/v3/api-docs/**"
    cors-allow-url:
      - ${CORS_ALLOW_URL_1:http://localhost:3000}
      - ${CORS_ALLOW_URL_2:http://localhost:8080}
      - ${CORS_ALLOW_URL_3:http://localhost:8081}
      - ${CORS_ALLOW_URL_4:http://localhost:8082}
      - ${CORS_ALLOW_URL_5:http://localhost:8083}
      - ${CORS_ALLOW_URL_6:http://localhost:8084}
      - ${CORS_ALLOW_URL_7:http://localhost:8085}
    clients:
      allowed:
        - ${SECURITY_CLIENT_ALLOWED:}
    scopes:
      read:
        - ${SECURITY_SCOPE_READ:}
      write:
        - ${SECURITY_SCOPE_WRITE:}
      delete:
        - ${SECURITY_SCOPE_DELETE:}
      update:
        - ${SECURITY_SCOPE_UPDATE:}

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017}
      database: ${MONGODB_DATABASE:mydb}

    redis:
      prefix: ${REDIS_PREFIX:app}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:default}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:30000}

  web:
    pageable:
      default-page-size: ${PAGE_SIZE_DEFAULT:10}
      max-page-size: ${PAGE_SIZE_MAX:100}
      one-indexed-parameters: ${PAGE_ONE_INDEXED:true}
      sort-parameter: ${PAGE_SORT_PARAMETER:id,asc}

feign:
  client:
    config:
      default:
        connect-timeout: ${FEIGN_CONNECT_TIMEOUT:30000}
        read-timeout: ${FEIGN_READ_TIMEOUT:30000}

rest-template:
  client:
    config:
      default:
        connect-timeout: ${REST_CONNECT_TIMEOUT:30000}
        read-timeout: ${REST_READ_TIMEOUT:30000}

springdoc:
  title: ${SPRINGDOC_TITLE:"MOS Core API"}
  description: ${SPRINGDOC_DESCRIPTION:"Core library providing common services and utilities"}
  version: ${SPRINGDOC_VERSION:"1.0.0"}
  contact:
    name: ${SPRINGDOC_CONTACT_NAME:"MOS Dev Team"}
    email: ${SPRINGDOC_CONTACT_EMAIL:"support@mos.vn"}
  license:
    name: ${SPRINGDOC_LICENSE_NAME:"MIT"}
    url: ${SPRINGDOC_LICENSE_URL:"https://opensource.org/licenses/MIT"}

logging:
  level:
    vn.mos.core: ${LOG_LEVEL:INFO}

server:
  port: ${SERVER_PORT:8081}
